import{a as q,S as P,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const $="50910167-da0c49dcf69b8279e7055dacc",M="https://pixabay.com/api/";async function p(s,o=1,r=40){const i={key:$,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:r};return(await q.get(M,{params:i})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),R=new P(".gallery a");function y(s){const o=s.map(({webformatURL:r,largeImageURL:i,tags:e,likes:t,views:n,comments:w,downloads:S})=>`
    <li class="photo-card">
      <a href="${i}">
        <img src="${r}" alt="${e}" />
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </a>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",o),R.refresh()}function B(){m.innerHTML=""}function L(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}function v(){g.classList.remove("is-hidden")}function l(){g.classList.add("is-hidden")}const E=document.querySelector(".form"),O=document.querySelector(".load-more");let u="",c=1;const d=40;let f=0;E.addEventListener("submit",async s=>{s.preventDefault();const o=s.target.elements["search-text"].value.trim();if(!o){a.warning({message:"Будь ласка, введіть слово для пошуку!",position:"topRight"});return}u=o,c=1,B(),l(),L();try{const r=await p(u,c,d);f=r.totalHits;const i=r.hits;i.length===0?(a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l()):(y(i),f>d&&v())}catch{a.error({message:"Сталася помилка. Спробуйте ще раз.",position:"topRight"})}finally{b()}});O.addEventListener("click",async()=>{c+=1,L(),l();try{const o=(await p(u,c,d)).hits;y(o);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),c*d>=f?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch{a.error({message:"Сталася помилка. Спробуйте ще раз.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
